version: 25
jobs:
- name: pusher all-branch commit
  steps:
  - !PushRepository
    name: force to gh pure-symbols/.github
    remoteUrl: https://github.com/pure-symbols/.github.git
    userName: yhm-amber
    passwordSecret: github.yhm-amber
    force: true
    condition: ALWAYS
  - !PushRepository
    name: force to cb pure-symbols/pure.symbols
    remoteUrl: https://codeberg.org/pure-symbols/pure.symbols.git
    userName: yhm
    passwordSecret: codeberg.yhm
    force: true
    condition: ALWAYS
  triggers:
  - !BranchUpdateTrigger
    projects: pure.symbols
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: puller all-branch cron.03:20:10
  steps:
  - !PullRepository
    name: from gh pure-symbols/.github
    remoteUrl: https://github.com/pure-symbols/.github.git
    syncToChildProject: false
    refs: refs/heads/* refs/tags/*
    withLfs: true
    force: true
    condition: ALWAYS
  - !PullRepository
    name: from cb pure-symbols/pure.symbols
    remoteUrl: https://codeberg.org/pure-symbols/pure.symbols.git
    syncToChildProject: false
    refs: refs/heads/* refs/tags/*
    withLfs: true
    force: true
    condition: ALWAYS
  triggers:
  - !ScheduleTrigger
    cronExpression: 10 20 3 * * ?
    projects: pure.symbols
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
